# docker-compose.yaml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: /api
        VITE_WS_BACKEND_URL: ws://${HOST:-localhost}/ws
    ports:
      - "80:80"
    environment:
      - MODEL_SIZE=${MODEL_SIZE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  default:
    driver: bridge